### ISSUE TITLE
dqn的代码错误

### ISSUE THREAD

**Issue by chzhan** [datawhalechina/easy-rl#100]
书还没看，跑了跑代码，dqn代码里，task1-task5都跑不通

**Comment by johnjim0816** [comment]
同学，暂时用task0和task1，现在有用了，代码近期在大迭代，所以可能误传了（

**Comment by johnjim0816** [comment]
> 书还没看，跑了跑代码，dqn代码里，task1-task5都跑不通

你好，已经解决～
