### ISSUE TITLE
Tutorial Notebook broken (Colab)

### ISSUE THREAD

**Issue by parsarahimi** [datawhalechina/easy-rl#102]
https://github.com/tensorflow/agents/blob/master/docs/tutorials/3_policies_tutorial.ipynb

Error on Imports code cell:
"TypeError: function() got an unexpected keyword argument 'reduce_retracing'"

**Comment by johnjim0816** [comment]
sorry for the later response, but the codes you cited are not developed from me ,thus I have no idea about it, sorry
