### ISSUE TITLE
电子书图片标注问题

### ISSUE THREAD

**Issue by Ashcaesar** [datawhalechina/easy-rl#104]
一个小问题，我下载的最新版的EasyR_v1.0.3的pdf，**2.3.6**节的**策略评估**部分，图2.14的两幅图片的位置错了，应该是（a）对应_人为控制船_，（b）对应_纸船_
![1](https://user-images.githubusercontent.com/65065458/175871621-1794472f-9cb1-4a94-bd43-681443807078.png)

**Comment by qiwang067** [comment]
@Ashcaesar 感谢您的纠错，相关问题已mark，pdf 在更新中~，下版的pdf版会纠正这个问题。
