### ISSUE TITLE
能否提供代码中主要库的版本

### ISSUE THREAD

**Issue by LeonardWan** [datawhalechina/easy-rl#105]
这对运行示例代码比较重要，例如python，gym，torch等库的具体版本

**Comment by johnjim0816** [comment]
目前开发版已经增加了conda的yaml和pip的requirements.txt，但是鉴于之前牵一发而动全身改动DQN一部分容易造成PPO的bug等等，还要再等一段时间更新到该仓库

**Comment by johnjim0816** [comment]
> 这对运行示例代码比较重要，例如python，gym，torch等库的具体版本

你好，已增加，可参考README
