### ISSUE TITLE
书写错误

### ISSUE THREAD

**Issue by tools-only** [datawhalechina/easy-rl#110]
pdf 36页：“给定动作之后状态之间的转移是确定的，例如p(2|6, u)=2” -> "p(2|6, u)=1"

**Comment by qiwang067** [comment]
@tools-only  感谢您的纠错:+1:，已经 mark 了，下个版本的 pdf 会修改这个错误

> pdf 36页：“给定动作之后状态之间的转移是确定的，例如p(2|6, u)=2” -> "p(2|6, u)=1"
