### ISSUE TITLE
Q-learning 出错

### ISSUE THREAD

**Issue by ZHUGUODONG1** [datawhalechina/easy-rl#111]
AttributeError: 'Config' object has no attribute 'save_fig'
这里plot_rewards函数里的cfg.save_fig应该改为cfg.save

**Comment by zl-yang** [comment]
uu，因为好像是A2C也要使用这个utils.py，如果这么改了，A2C运行报错，建议将Q-learning的task0.py中的class Config中的self.save改为self.save_fig
