### ISSUE TITLE
common文件夹里是不是少个py文件呀

### ISSUE THREAD

**Issue by zl-yang** [datawhalechina/easy-rl#112]
蒙特卡洛的文件里引用了plot.py，这里没有呀，请大佬更新一下~

**Comment by johnjim0816** [comment]
好的，在utils.py里面，最近在大版本更新，吸取之前的教训，在大更新完之前这个repo不会做更新，急的话可以看看开发版，在我的个人repo下面，https://github.com/johnjim0816/rl-tutorials

**Comment by zl-yang** [comment]
好的~谢谢uu的解答，辛苦啦



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月15日 15:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [datawhalechina/easy-rl] common文件夹里是不是少个py文件呀 (Issue #112) |

好的，在utils.py里面，最近在大版本更新，吸取之前的教训，在大更新完之前这个repo不会做更新，急的话可以看看开发版，在我的个人repo下面，https://github.com/johnjim0816/rl-tutorials
