### ISSUE TITLE
“3.3.1 蒙特卡洛策略评估”中经验均值问题

### ISSUE THREAD

**Issue by paulyzhangSmartNews** [datawhalechina/easy-rl#113]
在“3.3.1 蒙特卡洛策略评估”中，经验均值有这样一个表述”我们就可以把上一时刻的平均值与现在时刻的平均值建立联系“，这里想问下，是”上一时刻“呢，还是指”样本“，指上个回合中该s状态的样本？

**Comment by qiwang067** [comment]
@paulyzhangSmartNews  感谢您的反馈，这边指的就是样本

**Comment by paulyzhangSmartNews** [comment]
Thank you!

**Comment by qiwang067** [comment]
> Thank you!

:blush:
