### ISSUE TITLE
PPO advantage calculation

### ISSUE THREAD

**Issue by XinXU-USTC** [datawhalechina/easy-rl#114]
I think that in ppo2.py line119-122, we need to assert "if dones_arr[k]: break" into the for loop.
That is because there are data from different episodes in the memory.
Is it right?

**Comment by johnjim0816** [comment]
> I think that in ppo2.py line119-122, we need to assert "if dones_arr[k]: break" into the for loop. That is because there are data from different episodes in the memory. Is it right?

yes
