### ISSUE TITLE
conda的环境需要换成python==3.8了

### ISSUE THREAD

**Issue by ExileSaber** [datawhalechina/easy-rl#115]
envs中的README.md中创建虚拟环境的语句要换成conda create -n easyrl python=3.8，3.8以下的版本都不支持gym了

**Comment by johnjim0816** [comment]
> envs中的README.md中创建虚拟环境的语句要换成conda create -n easyrl python=3.8，3.8以下的版本都不支持gym了

哪里看到的消息，，
