### ISSUE TITLE
1.7.1 Gym示例 返回值增多了

### ISSUE THREAD

**Issue by neverevergiveup** [datawhalechina/easy-rl#126]
原代码：
```
import gym  
env = gym.make('CartPole-v0')  
env.reset()  
for _ in range(1000):
    env.render()  
    action = env.action_space.sample() 
    observation, reward, done, info = env.step(action)
    print(observation)
env.close()    
```

报错：
> ValueError                                Traceback (most recent call last)
> Cell In [7], line 8
>       6     action = env.action_space.sample()  # 从动作空间中选取一个动作
>       7     print(action)
> ----> 8     observation, reward, done, info = env.step(action)   # 用于提交动作,括号内是具体的动作
>       9     print(observation)
>      10 env.close
> 
> ValueError: too many values to unpack (expected 4)

实际的返回值应该是5个：
``print(env.step(action))
``(array([-0.02054064, -0.15305778,  0.04347553,  0.29886863], dtype=float32), 1.0, False, False, {})

**Comment by qiwang067** [comment]
这是 Gym 版本问题，前文交代过，具体见下图：
![image](https://user-images.githubusercontent.com/22296010/216922085-08d76659-a93b-457a-94ac-013d97ad489d.png)





> 原代码：
> 
> ```
> import gym  
> env = gym.make('CartPole-v0')  
> env.reset()  
> for _ in range(1000):
>     env.render()  
>     action = env.action_space.sample() 
>     observation, reward, done, info = env.step(action)
>     print(observation)
> env.close()    
> ```
> 
> 报错：
> 
> > ValueError                                Traceback (most recent call last)
> > Cell In [7], line 8
> > 6     action = env.action_space.sample()  # 从动作空间中选取一个动作
> > 7     print(action)
> > ----> 8     observation, reward, done, info = env.step(action)   # 用于提交动作,括号内是具体的动作
> > 9     print(observation)
> > 10 env.close
> > ValueError: too many values to unpack (expected 4)
> 
> 实际的返回值应该是5个： `print(env.step(action)) `(array([-0.02054064, -0.15305778, 0.04347553, 0.29886863], dtype=float32), 1.0, False, False, {})

**Comment by neverevergiveup** [comment]
![图片](https://user-images.githubusercontent.com/40696099/216922763-71f85b9a-844c-4854-834e-d522e5790507.png)

谢谢！我看的v1.0.4的PDF内没有说明这个问题。

**Comment by qiwang067** [comment]
> ![图片](https://user-images.githubusercontent.com/40696099/216922763-71f85b9a-844c-4854-834e-d522e5790507.png)
> 
> 谢谢！我看的v1.0.4的PDF内没有说明这个问题。

嗯嗯~，下回更新 PDF，这个错误修改一下
