### ISSUE TITLE
第四章图4.10标注是不是有误？

### ISSUE THREAD

**Issue by njwm** [datawhalechina/easy-rl#127]
第四章图4.10（pdf文档P77），箭头指向的右图  “但是实际上......”  这几个字的标注是不是不对啊？
整个图都是理想例子吧？左边是提高前，右边是提高后；并不是右侧是“实际上”的不理想例子吧？
“实际上”的不理想例子应该是图4.11
所以现在这样的标注有点容易产生歧义，让人不好理解

**Comment by qiwang067** [comment]
@njwm  感谢您的勘误:+1:，纸质版对应的勘误表已更新，具体修改可参见：https://datawhalechina.github.io/easy-rl/#/errata，
pdf 将会在下次更新时修正这个错误
