### ISSUE TITLE
Edit problem in Chapter3

### ISSUE THREAD

**Issue by mvllwong** [datawhalechina/easy-rl#128]
[CliffWalking-v0环境简介](https://datawhalechina.github.io/easy-rl/#/chapter3/project1?id=cliffwalking-v0%e7%8e%af%e5%a2%83%e7%ae%80%e4%bb%8b)
这个强化游戏的简介：“首先对该环境做一个简介，该环境中文名称叫悬崖寻路问题（CliffWalking），是指在一个4 x 12的网格中，智能体以网格的左下角位置为起点，以网格的下角位置为终点，目标是移动智能体到达终点位置，智能体每次可以在上、下、左、右这4个方向中移动一步，每移动一步会得到-1单位的奖励。”
中“智能体以网格的左下角位置为起点，以网格的下角位置为终点
缺少一个右字，应该为➡
智能体以网格的左下角位置为起点，以网格的右下角位置为终点

**Comment by johnjim0816** [comment]
> [CliffWalking-v0环境简介](https://datawhalechina.github.io/easy-rl/#/chapter3/project1?id=cliffwalking-v0%e7%8e%af%e5%a2%83%e7%ae%80%e4%bb%8b) 这个强化游戏的简介：“首先对该环境做一个简介，该环境中文名称叫悬崖寻路问题（CliffWalking），是指在一个4 x 12的网格中，智能体以网格的左下角位置为起点，以网格的下角位置为终点，目标是移动智能体到达终点位置，智能体每次可以在上、下、左、右这4个方向中移动一步，每移动一步会得到-1单位的奖励。” 中“智能体以网格的左下角位置为起点，以网格的下角位置为终点 缺少一个右字，应该为➡ 智能体以网格的左下角位置为起点，以网格的右下角位置为终点

感谢勘误，已改
