### ISSUE TITLE
随书代码在哪

### ISSUE THREAD

**Issue by GoWithWind2015** [datawhalechina/easy-rl#129]
书上的随书代码： 如P68的3.5.3 Q学习算法choose_action函数在代码仓库找不到，代码仓库的jupyter代码和书上不对应。

**Comment by qiwang067** [comment]
目前的 GitHub 代码已更新，跟之前的附书代码有些区别，如果想看附书代码的话，可通过如下链接下载：
https://box.lenovo.com/l/T55HG0

**Comment by GoWithWind2015** [comment]
@qiwang067 好的，感谢

**Comment by qiwang067** [comment]
@GoWithWind2015 客气啦~
> @qiwang067 好的，感谢

**Comment by chensisi0730** [comment]
所以GitHub和附书代码不是一套代码？那么GitHub上的是什么代码？

**Comment by qiwang067** [comment]
> 所以GitHub和附书代码不是一套代码？那么GitHub上的是什么代码？

更新迭代后的代码

**Comment by chensisi0730** [comment]
意思书上的代码很老了，没有更新，GitHub上的是更新的？
