### ISSUE TITLE
第五章勘误

### ISSUE THREAD

**Issue by notomatoes** [datawhalechina/easy-rl#130]
https://datawhalechina.github.io/easy-rl/#/chapter5/chapter5:~:text=%E9%83%BD%E6%98%AF%E4%B8%8D%E9%94%99%E7%9A%84%EF%BC%8C-,%E5%8D%B3%E6%97%B6,-%E4%B8%8D%E6%98%AF%E6%9C%80%E5%A5%BD%E7%9A%84%EF%BC%8C%E4%B9%9F%E6%98%AF  
即时 -> 即使   是不是打错了

**Comment by qiwang067** [comment]
@notomatoes，感谢您的勘误，错误已纠正。

> https://datawhalechina.github.io/easy-rl/#/chapter5/chapter5:~:text=%E9%83%BD%E6%98%AF%E4%B8%8D%E9%94%99%E7%9A%84%EF%BC%8C-,%E5%8D%B3%E6%97%B6,-%E4%B8%8D%E6%98%AF%E6%9C%80%E5%A5%BD%E7%9A%84%EF%BC%8C%E4%B9%9F%E6%98%AF 即时 -> 即使 是不是打错了
