### ISSUE TITLE
添加参考文献

### ISSUE THREAD

**Issue by RudyGuo** [datawhalechina/easy-rl#133]
https://github.com/datawhalechina/easy-rl/blob/master/notebooks/DQN.ipynb
与https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html
基本一致，可以加个参考。

**Comment by johnjim0816** [comment]
> https://github.com/datawhalechina/easy-rl/blob/master/notebooks/DQN.ipynb 与https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html 基本一致，可以加个参考。

您再仔细看看？
