### ISSUE TITLE
最新的版本，可以出PDF吗

### ISSUE THREAD

**Issue by chensisi0730** [datawhalechina/easy-rl#137]
最新的版本，可以出PDF吗？ 1.04错误太多了

**Comment by qiwang067** [comment]
建议您先看在线版（在线版的错误是实时更新），pdf v1.0.4 版的错误已经收集，等有空了会对目前版本的错误进行修正，出新一版的 pdf，另外，纸质书配有专门的勘误表：https://datawhalechina.github.io/easy-rl/#/errata，您也可以参考这个

**Comment by qiwang067** [comment]
已更新最新版的 pdf，具体可见：
https://github.com/datawhalechina/easy-rl/releases

**Comment by qiwang067** [comment]
> 建议您先看在线版（在线版的错误是实时更新），pdf v1.0.4 版的错误已经收集，等有空了会对目前版本的错误进行修正，出新一版的 pdf，另外，纸质书配有专门的勘误表：https://datawhalechina.github.io/easy-rl/#/errata 您也可以参考这个
> 
> > 最新的版本，可以出PDF吗？ 1.04错误太多了



> 最新的版本，可以出PDF吗？ 1.04错误太多了

已更新最新的 pdf 版本，具体可见：
https://github.com/datawhalechina/easy-rl/releases
