### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by ConnorSiXiong** [datawhalechina/easy-rl#139]
在第三章 表格型方法 3.3.2 时序差分

这里应该是“中性刺激”，而不是“中件刺激”
![image](https://github.com/datawhalechina/easy-rl/assets/52727136/85a5356d-aee2-42b4-8013-fde6c667911c)

**Comment by qiwang067** [comment]
> 在第三章 表格型方法 3.3.2 时序差分
> 
> 这里应该是“中性刺激”，而不是“中件刺激” ![image](https://user-images.githubusercontent.com/52727136/253472894-85a5356d-aee2-42b4-8013-fde6c667911c.png)
@ConnorSiXiong 感谢您的纠错，pdf 版下次更新时，将会修正这个错误 👍

**Comment by qiwang067** [comment]
> > 在第三章 表格型方法 3.3.2 时序差分
> > 这里应该是“中性刺激”，而不是“中件刺激” ![image](https://user-images.githubusercontent.com/52727136/253472894-85a5356d-aee2-42b4-8013-fde6c667911c.png)
> 
> @ConnorSiXiong 感谢您的纠错，pdf 版下次更新时，将会修正这个错误 👍

已更新最新的 pdf 版本，具体可见：
https://github.com/datawhalechina/easy-rl/releases
