### ISSUE TITLE
关于条件全期望公式的推导的问题

### ISSUE THREAD

**Issue by SacuraA** [datawhalechina/easy-rl#152]
书的39的推到中
$/sum_y E(x|y)*p(y|z)$  为什么等于$/sum_y /sum_x x*p(x|y,z)*p(y|z)$ ，这个地方将E(X|Y)看作y的函数展开不应该是x*p(x|y)吗为什么是p(x|y,z)

**Comment by qiwang067** [comment]
推荐您看这个：https://github.com/datawhalechina/easy-rl/issues/36#issuecomment-1155146514
