### ISSUE TITLE
notebooks/Q-learning/QLearning.ipynb的绘图代码存在一个小瑕疵

### ISSUE THREAD

**Issue by 976213951** [datawhalechina/easy-rl#153]
作者您好，首先十分感谢您的学习资源，对我这种入门小白十分友好。但最近我运行代码时发现了一个小瑕疵。
在“4、设置参数”的“def plot_rewards(rewards,title="learning curve")"中， 对x轴的范围限制代码：“plt.xlim(0, len(rewards), 10)”在运行时会发生报错。
通过我个人网上资料的收集，我理解为xlim只能接收两个参数（x的左边界/下界，x的有边界/上界），而作者提供的代码多了一个参数传入。另外，结合我对代码的理解和大佬给出的plot图像，我认为应该删除此处的“10”，既将源代码改为“plt.xlim(0, len(rewards))”。
经过验证，此时代码能够正常运行，并且绘制的图像与作者给出的样例一致。

**Comment by qiwang067** [comment]
@976213951  感谢您的反馈 👍 ，代码已修改，具体见：https://github.com/datawhalechina/easy-rl/blob/master/notebooks/Q-learning/QLearning.ipynb
