### ISSUE TITLE
《9.3 优势演员-评论员算法》的公式（9.3）错误

### ISSUE THREAD

**Issue by Sjtu-hyg** [datawhalechina/easy-rl#155]
Q和V的关系中，是否V前缺少了折扣系数γ

**Comment by Sjtu-hyg** [comment]
另外，书中关于(st, at, rt+1, st+1, at+1) 中rt+1的下标是否没有统一，例如在《3.4.1Sarsa：同策略时序差分控制》中采用rt+1，而在《9.3优势演员-评论员算法》中如公式（9.3）采用(st, at, rt, st+1, at+1) 的顺序

**Comment by qiwang067** [comment]
> Q和V的关系中，是否V前缺少了折扣系数γ

这边为了简化，没有写折扣因子
