### ISSUE TITLE
关于全书结构的建议

### ISSUE THREAD

**Issue by chenslcool** [datawhalechina/easy-rl#161]
如题，感觉目录组织逻辑不够清晰。
DQN放在“表格型方法”后一章比较合适吧？
而且这三者，都是深度Q网络，放在同一章递进组织比较合适？
![image](https://github.com/user-attachments/assets/de926aea-983b-46c7-bdf9-83fc71c20c05)

**Comment by qiwang067** [comment]
> 如题，感觉目录组织逻辑不够清晰。 DQN放在“表格型方法”后一章比较合适吧？ 而且这三者，都是深度Q网络，放在同一章递进组织比较合适？ ![image](https://private-user-images.githubusercontent.com/40563358/351349201-de926aea-983b-46c7-bdf9-83fc71c20c05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODgxNjYsIm5iZiI6MTcyMTc4Nzg2NiwicGF0aCI6Ii80MDU2MzM1OC8zNTEzNDkyMDEtZGU5MjZhZWEtOTgzYi00NmM3LWJkZjktODNmYzcxYzIwYzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAyMjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYzk5Yzc0YzE3YTM1NmQ0YTVhMzViM2UyN2E4NzdkMmU2NzBmMjYwZjViNzQzM2YzYmRjMzE5OGQ4ODU1MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJwPUwlIJ41PHuWXYOphZb9cPmgfpcYV9zXkp9P3o68)

@chenslcool 感谢您的反馈~

Q1：DQN放在“表格型方法”后一章比较合适吧？
A1：我们的逻辑是传统强化学习方法→基于策略的深度强化学习方法→基于价值的深度强化学习方法

Q2：而且这三者，都是深度Q网络，放在同一章递进组织比较合适？
A2：之前是考虑都放在一起，篇幅可能过长，后面的版本可以考虑合并下
