### ISSUE TITLE
第三章第四节书中60页价值函数是单调的证明过程是不是有问题？

### ISSUE THREAD

**Issue by lixinliu1995** [datawhalechina/easy-rl#163]
![image](https://github.com/user-attachments/assets/352fc80d-f46d-4b4c-9eea-28b34e2901a3)

上面红框式子是取Q函数的最大值；下面红框式子中对Q函数进行了加权求和，π函数减去一个很小的数，除以一个比1小的数。我想问下这不等式是怎么成立的？

**Comment by lixinliu1995** [comment]
![image](https://github.com/user-attachments/assets/b506367f-634d-482f-8105-b7138e323c54)
补充

**Comment by qiwang067** [comment]
@lixinliu1995 您可以参考下面的推导过程：

<img width="740" alt="image" src="https://github.com/user-attachments/assets/6ee05eda-a9c3-4d01-abfc-0924268c315c">

![image](https://github.com/user-attachments/assets/e4091ec7-7f51-42c6-adad-23c701462d11)
