### ISSUE TITLE
There are one suggestion for a word  

### ISSUE THREAD

**Issue by shi-yang999** [datawhalechina/easy-rl#165]
![image](https://github.com/user-attachments/assets/85a693e5-574e-40af-b599-59c504ed66f4)

I think that it's right "deep reinforcement learning".

**Comment by qiwang067** [comment]
> ![image](https://private-user-images.githubusercontent.com/66561819/378695498-85a693e5-574e-40af-b599-59c504ed66f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Nzc1MTcsIm5iZiI6MTcyOTU3NzIxNywicGF0aCI6Ii82NjU2MTgxOS8zNzg2OTU0OTgtODVhNjkzZTUtNTc0ZS00MGFmLWI1OTktNTljNTA0ZWQ2NmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA2MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmODM1YjEzMTQyOTE2ODQ5M2JiNWMzMWI5NzAwZmZlZmE0MmEyMTgxN2VjMzViOTAwYmExYTI5MDU3YTAwZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oE06SvfOe8sZNzH9atK-udRA-Z6PCqizU_90Bw4Xbkw)
> 
> I think that it's right "deep reinforcement learning".

@shi-yang999 感谢您的反馈，在线版错误已修改，pdf 版会在下个更新时修改

**Comment by shi-yang999** [comment]
It's my pleasure!
