### ISSUE TITLE
这个地方报错，我需要安装什么

### ISSUE THREAD

**Issue by lmc19970711** [datawhalechina/easy-rl#24]
![image](https://user-images.githubusercontent.com/57525636/112076847-25d5a800-8bb6-11eb-9c97-e0b67a81191f.png)
![image](https://user-images.githubusercontent.com/57525636/112076863-32f29700-8bb6-11eb-89ce-41680bc636ad.png)

**Comment by JohnJim0816** [comment]
在codes路径下运行main.py试试？

**Comment by DeepZheng** [comment]
先确定cwd路径是fileDirname，然后把env文件夹改个名试试

**Comment by JohnJim0816** [comment]
现在应该在任意路径下运行main.py都可以了
