### ISSUE TITLE
/codes/PPO/main.py syntax error

### ISSUE THREAD

**Issue by Ynjxsjmh** [datawhalechina/easy-rl#25]
https://github.com/datawhalechina/easy-rl/blob/e4690ac89f14166731994d6a0b5a50cede341f67/codes/PPO/main.py#L77-L81

On Line 78 and L79

**Comment by JohnJim0816** [comment]
已更新，重新pull试试

**Comment by Ynjxsjmh** [comment]
Thanks, fixed on [ed7b60f](https://github.com/datawhalechina/easy-rl/commit/ed7b60fd5b8f66c87a54068f242fa464d1e3fc4a).
