### ISSUE TITLE
对bootstrapping(拔靴自助)翻译的一点想法

### ISSUE THREAD

**Issue by AA1HSHH** [datawhalechina/easy-rl#27]
你好，谢谢你们的项目，我学到了很多。
或许第二章节的Iterative Algorithm for Computing Value of a MRP这里的bootstrapping(拔靴自助)应该翻译为自举吗？
我参考的是Reinforcement Learning an introduction的翻译版强化学习(第二版)第87页第三段第三行的翻译，感觉这样顺口点，bootstrapping(拔靴自助)有点奇怪。

**Comment by qiwang067** [comment]
感谢您的指正，笔记已更新
