### ISSUE TITLE
Markov Decision Process中的Reward函数

### ISSUE THREAD

**Issue by Leoluo0320** [datawhalechina/easy-rl#63]
记忆中Reward函数通常定义为离开某个状态时获得的Reward，在第二章MDP的笔记中
![image](https://user-images.githubusercontent.com/45347246/121490419-8cc16b00-ca07-11eb-939f-beb11aa8ebee.png)

![image](https://user-images.githubusercontent.com/45347246/121492199-410fc100-ca09-11eb-888f-8a727c877ff0.png)
在上图中 E[Rt+1|st=s] = R(s)， 是否可以推出R(s)为离开状态s时的奖励

请指教 谢谢

**Comment by qiwang067** [comment]
> 记忆中Reward函数通常定义为离开某个状态时获得的Reward，在第二章MDP的笔记中
> ![image](https://user-images.githubusercontent.com/45347246/121490419-8cc16b00-ca07-11eb-939f-beb11aa8ebee.png)
> 
> ![image](https://user-images.githubusercontent.com/45347246/121492199-410fc100-ca09-11eb-888f-8a727c877ff0.png)
> 在上图中 E[Rt+1|st=s] = R(s)， 是否可以推出R(s)为离开状态s时的奖励
> 
> 请指教 谢谢

![image](https://user-images.githubusercontent.com/22296010/121638044-e9329200-cabc-11eb-8a6e-353df20c4611.png)
