### ISSUE TITLE
为什么DQNchoose_action需要消除梯度

### ISSUE THREAD

**Issue by heyfavour** [datawhalechina/easy-rl#64]
我看demo中，dqn在predict时候需torch.no_grad，想知道这个是为什么，同时我看到其他人的demo中，用的model.forward但是没有使用no_grad，所以对挺困惑的

**Comment by JohnJim0816** [comment]
> 我看demo中，dqn在predict时候需torch.no_grad，想知道这个是为什么，同时我看到其他人的demo中，用的model.forward但是没有使用no_grad，所以对挺困惑的

这个进一步加速和节省gpu空间，可用可不用的

**Comment by heyfavour** [comment]
> > 我看demo中，dqn在predict时候需torch.no_grad，想知道这个是为什么，同时我看到其他人的demo中，用的model.forward但是没有使用no_grad，所以对挺困惑的
> 
> 这个进一步加速和节省gpu空间，可用可不用的

OK 博主啥时候更新一下Categorical_DQN的demo，网上有些代码看了还是比较懵懂==
