### ISSUE TITLE
add PPO-continuous code

### ISSUE THREAD

**Issue by heyfavour** [datawhalechina/easy-rl#68]
可以新增PPO-continuous的demo code么

**Comment by JohnJim0816** [comment]
好的，会的

**Comment by qiwang067** [comment]
> 可以新增PPO-continuous的demo code么

@heyfavour 您可以参考这个：
https://github.com/datawhalechina/joyrl-book/blob/main/notebooks/%E7%AC%AC12%E7%AB%A0_PPO_Pendulum-v1.ipynb
