### ISSUE TITLE
Qlearning error

### ISSUE THREAD

**Issue by HRXWEB** [datawhalechina/easy-rl#70]
当我运行`task0_train.py`文件时会报错：
`PermissionError: [errno 13] Permission denied: '/outputs'`

https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L12-L15

您好，我不知道我这么理解对不对：
按照您的命名方式
L13应该改为
```
curr_path  = os.path.abspath(os.path.dirname(__file__))
```
否则的话我打印出来看到`curr_path = ' '`，这样的话在
https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L32-L33
https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L108
就会出现问题，因为没有办法直接在根目录？或者哪个目录直接创建`/outputs/******`

**Comment by JohnJim0816** [comment]
> 当我运行`task0_train.py`文件时会报错：
> `PermissionError: [errno 13] Permission denied: '/outputs'`
> 
> https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L12-L15
> 
> 您好，我不知道我这么理解对不对：
> 按照您的命名方式
> L13应该改为
> 
> ```
> curr_path  = os.path.abspath(os.path.dirname(__file__))
> ```
> 
> 否则的话我打印出来看到`curr_path = ' '`，这样的话在
> https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L32-L33
> 
> 
> https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L108
> 
> 
> 就会出现问题，因为没有办法直接在根目录？或者哪个目录直接创建`/outputs/******`

curr_path路径已作修改，关于你的问题，除了这个之外，还有可能你系统没项目路径的权限，你是什么系统呢？可以先pull新代码跑起来试试

**Comment by HRXWEB** [comment]
> > 当我运行`task0_train.py`文件时会报错：
> > `PermissionError: [errno 13] Permission denied: '/outputs'`
> > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L12-L15
> > 
> > 您好，我不知道我这么理解对不对：
> > 按照您的命名方式
> > L13应该改为
> > ```
> > curr_path  = os.path.abspath(os.path.dirname(__file__))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 否则的话我打印出来看到`curr_path = ' '`，这样的话在
> > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L32-L33
> > 
> > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L108
> > 
> > 就会出现问题，因为没有办法直接在根目录？或者哪个目录直接创建`/outputs/******`
> 
> curr_path路径已作修改，关于你的问题，除了这个之外，还有可能你系统没项目路径的权限，你是什么系统呢？可以先pull新代码跑起来试试

没有什么问题了，我按照自己的写法当时改了curr path也已经能够训起来了。
可能是我没有表述清楚，我的意思是如果没有加上`os.path.abspath()`的话，当执行下面两句的时候
> > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L32-L33
新建的目录是`outputs/cliff***/***/***/` 它是和`home`目录同一级的，应该是没有权限修改的

**Comment by JohnJim0816** [comment]
> > > 当我运行`task0_train.py`文件时会报错：
> > > `PermissionError: [errno 13] Permission denied: '/outputs'`
> > > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L12-L15
> > > 
> > > 您好，我不知道我这么理解对不对：
> > > 按照您的命名方式
> > > L13应该改为
> > > ```
> > > curr_path  = os.path.abspath(os.path.dirname(__file__))
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 否则的话我打印出来看到`curr_path = ' '`，这样的话在
> > > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L32-L33
> > > 
> > > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L108
> > > 
> > > 就会出现问题，因为没有办法直接在根目录？或者哪个目录直接创建`/outputs/******`
> > 
> > 
> > curr_path路径已作修改，关于你的问题，除了这个之外，还有可能你系统没项目路径的权限，你是什么系统呢？可以先pull新代码跑起来试试
> 
> 没有什么问题了，我按照自己的写法当时改了curr path也已经能够训起来了。
> 可能是我没有表述清楚，我的意思是如果没有加上`os.path.abspath()`的话，当执行下面两句的时候
> 
> > > https://github.com/datawhalechina/easy-rl/blob/be3b6db203dce2de99ea8c95bddde8b9a0501c5b/codes/QLearning/task0_train.py#L32-L33
> > > 
> > > 新建的目录是`outputs/cliff***/***/***/` 它是和`home`目录同一级的，应该是没有权限修改的

是的，我一般直接用vscode右上角的按钮运行的，后面考虑到直接终端命令执行的话，原先路径就不行了，感谢你的建议
