### ISSUE TITLE
DQN代码中有bug

### ISSUE THREAD

**Issue by PungTeng** [datawhalechina/easy-rl#71]
在agent.py中的update函数中

原代码为：
` if len(self.memory) < self.batch_size:
            return`

应改为：
` if len(self.buffer.memory) < self.batch_size:
            return`

**Comment by JohnJim0816** [comment]
> 在agent.py中的update函数中
> 
> 原代码为：
> ` if len(self.memory) < self.batch_size: return`
> 
> 应改为：
> ` if len(self.buffer.memory) < self.batch_size: return`

我并没有在DQN类中定义buffer啊，就是memory，运行正常，同学遇到了什么问题呢

**Comment by PungTeng** [comment]
不好意思，提的issues没说明问题，源代码中
`if len(self.memory) < self.batch_size: return`

会报错以下问题

```
if len(self.memory) < self.batch_size:
TypeError: object of type 'ReplayBuffer' has no len()
```

后来查到是代码中`self.memory=ReplayBuffer`这个类的，len方法不能用在这个类，要把`replaybuffer`里面的`buffer`引出来才能用`len`

所以当我改成
`if len(self.memory.buffer) < self.batch_size:`
程序才可以正常运行

我的运行环境是mac m1，pycharm。

不知道您那边是否会有出现这样的问题。

**Comment by JohnJim0816** [comment]
> 不好意思，提的issues没说明问题，源代码中
> `if len(self.memory) < self.batch_size: return`
> 
> 会报错以下问题
> 
> ```
> if len(self.memory) < self.batch_size:
> TypeError: object of type 'ReplayBuffer' has no len()
> ```
> 
> 后来查到是代码中`self.memory=ReplayBuffer`这个类的，len方法不能用在这个类，要把`replaybuffer`里面的`buffer`引出来才能用`len`
> 
> 所以当我改成
> `if len(self.memory.buffer) < self.batch_size:`
> 程序才可以正常运行
> 
> 我的运行环境是mac m1，pycharm。
> 
> 不知道您那边是否会有出现这样的问题。

同学我这个是真的一点问题也没有，你在pull一下，可能之前更新了一版错误的代码
