### ISSUE TITLE
运行程序会有找不到字体包的错误

### ISSUE THREAD

**Issue by LearnAlgorithmMan** [datawhalechina/easy-rl#72]
在win10运行时，跑了Q-learning和DQN的程序，前半段在训练的时候是正常的，到后半段要训练的时候，
总会出现错误FileNotFoundError: [Errno 2] No such file or directory: 'D:\\System\\Library\\Fonts\\STHeiti Light.ttc'
![image](https://user-images.githubusercontent.com/58768401/136655088-c1ce0ed7-96de-412c-b746-a7c078d079f6.png)
![image](https://user-images.githubusercontent.com/58768401/136655152-f67f95e5-e234-4ee6-9290-387bdad32a66.png)

**Comment by JohnJim0816** [comment]
> 在win10运行时，跑了Q-learning和DQN的程序，前半段在训练的时候是正常的，到后半段要训练的时候， 总会出现错误FileNotFoundError: [Errno 2] No such file or directory: 'D:\System\Library\Fonts\STHeiti Light.ttc' ![image](https://user-images.githubusercontent.com/58768401/136655088-c1ce0ed7-96de-412c-b746-a7c078d079f6.png) ![image](https://user-images.githubusercontent.com/58768401/136655152-f67f95e5-e234-4ee6-9290-387bdad32a66.png)

这部分是因为加入了中文画图，可以在plot.py将相应的STHeiti部分注释掉就好，笔者用的mac没考虑windows上的问题抱歉啦，或许你可以下载相应字体放到文件中去
