### ISSUE TITLE
plot_rewards（）函数错误

### ISSUE THREAD

**Issue by daihuiao** [datawhalechina/easy-rl#75]
代码中有两种plot_rewards（）函数的使用，传入的参数不一样，但是在common中的plot.py 文件中只有一个plot_rewards的实现。

**Comment by johnjim0816** [comment]
> 代码中有两种plot_rewards（）函数的使用，传入的参数不一样，但是在common中的plot.py 文件中只有一个plot_rewards的实现。

具体哪里呢

**Comment by daihuiao** [comment]
似乎已经修改了，优秀！
