### ISSUE TITLE
请问为什么在这agent中的update计算discount reward时要对reward为0情况进行特别考虑？

### ISSUE THREAD

**Issue by wansiwei0521** [datawhalechina/easy-rl#77]
https://github.com/datawhalechina/easy-rl/blob/67eff6252b4681baedf36c103ebc1b8a76359627/codes/PolicyGradient/agent.py#L37-L44

**Comment by johnjim0816** [comment]
这个reward等于0应该是一个回合结束的标志，这个的reward_pool实际上包含多个回合，但是计算discount reward应该是一个回合为单位～
