### ISSUE TITLE
DDPG的代码有很多纰漏

### ISSUE THREAD

**Issue by liuchaohu** [datawhalechina/easy-rl#84]
运行DDPG中的`task0.py`会报不少错误，不过调整下应该能运行，希望作者有时间可以更新下代码

**Comment by johnjim0816** [comment]
> 运行DDPG中的`task0.py`会报不少错误，不过调整下应该能运行，希望作者有时间可以更新下代码

好的，中途部分更新可能有些遗漏，谢谢反馈～

**Comment by liuchaohu** [comment]
> > 运行DDPG中的`task0.py`会报不少错误，不过调整下应该能运行，希望作者有时间可以更新下代码
> 
> 好的，中途部分更新可能有些遗漏，谢谢反馈～

感谢作者提供的代码，对初学者帮助非常大！
