### ISSUE TITLE
reinforcement拼写错误

### ISSUE THREAD

**Issue by yintianan** [datawhalechina/easy-rl#89]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/39551770/160597721-61d37b5c-c3d8-46d2-b475-840cf1bdd3fd.png">

**Comment by qiwang067** [comment]
感谢您的纠错，错误已纠正，内容已更新。

**Comment by qiwang067** [comment]
> <img alt="image" width="1400" src="https://user-images.githubusercontent.com/39551770/160597721-61d37b5c-c3d8-46d2-b475-840cf1bdd3fd.png">

感谢您的纠错，错误已修改，内容已更新 XD
