### ISSUE TITLE
QLearning算法可能出现的bug

### ISSUE THREAD

**Issue by stellar749** [datawhalechina/easy-rl#90]
在QLearning算法中的train.py中没有对每次迭代的agent.sample_count清零，这样在整个train过程的400个epoch中，choose_action函数中的agent.sample_count一直在增加

**Comment by johnjim0816** [comment]
> 在QLearning算法中的train.py中没有对每次迭代的agent.sample_count清零，这样在整个train过程的400个epoch中，choose_action函数中的agent.sample_count一直在增加

这个sample count就是在训练过程中不断叠加的，有些地方叫frame_idx，如果清零的话，e-greedy策略的epsilon就不会不断重置为初始值
