### ISSUE TITLE
68页的代码块缩进错误

### ISSUE THREAD

**Issue by xiaoqingsai** [datawhalechina/easy-rl#92]
3.5.2 强化学习基本接口  的最后一个代码块的最后两行的缩进应该有问题
![屏幕截图 2022-04-21 160500](https://user-images.githubusercontent.com/45195493/164410268-8077edc6-15e3-4c21-89d6-6d102b2b9576.png)

**Comment by qiwang067** [comment]
> 3.5.2 强化学习基本接口 的最后一个代码块的最后两行的缩进应该有问题 ![屏幕截图 2022-04-21 160500](https://user-images.githubusercontent.com/45195493/164410268-8077edc6-15e3-4c21-89d6-6d102b2b9576.png)

@xiaoqingsai 感谢您的纠错:thumbsup: ，下次 pdf 版更新时会修改这个错误，
