### ISSUE TITLE
电子版第40页，策略符号是否出错？

### ISSUE THREAD

**Issue by QUIlToT** [datawhalechina/easy-rl#93]
作者您好，策略应该是（a|s）吧，这里是不是打错了呢？
![微信图片编辑_20220427145129](https://user-images.githubusercontent.com/72594017/165458712-c75dc378-2a0b-4e9c-9952-11c54648af1b.jpg)

**Comment by qiwang067** [comment]
@QUIlToT 感谢您的纠错 👍 ，确实应该是 π(a|s)，错误会在下次电子版更新时纠正。
