### ISSUE TITLE
伪代码错误

### ISSUE THREAD

**Issue by QUIlToT** [datawhalechina/easy-rl#94]
作者您好，我发现这个伪代码的表述存在问题，我特意翻了一下RL: AI （Richard S. Sutton）

本书：
<img width="721" alt="微信截图_20220429151315" src="https://user-images.githubusercontent.com/72594017/165899964-9c5911b2-9303-453c-9a9e-bc941e050d16.png">

RL: AI：
<img width="876" alt="微信截图_20220429151341" src="https://user-images.githubusercontent.com/72594017/165900030-451a08cb-4ff0-4bb4-99a8-1ef98cb9ad86.png">
 
标记位置应该是判断出现此种情况，而不是“没有出现”，不知道我理解的对不对。

而且，还有一个问题想请教，希望能得到您的回复。以下两个函数按顺序分别为Q-learning和Sarsa选择action的方式：

<img width="712" alt="微信截图_20220429152659" src="https://user-images.githubusercontent.com/72594017/165901590-28bfd36e-8274-48eb-b2b8-a56e0ee2f18d.png">

<img width="799" alt="微信截图_20220429152727" src="https://user-images.githubusercontent.com/72594017/165901640-d956525c-7909-4957-8c55-eeb5b3f5d1be.png">

请问是e-greedy 策略的两种实现方法吗？ 谢谢！

**Comment by qiwang067** [comment]
> > 
> 
> 那请问您方便回答一下我的问题吗？上图中的代码是本书配套的代码。

代码的作者 @johnjim0816 会回答您的问题。

**Comment by QUIlToT** [comment]
> > > 
> > 
> > 
> > 那请问您方便回答一下我的问题吗？上图中的代码是本书配套的代码。
> 
> 代码的作者 @johnjim0816 会回答您的问题。

好的，谢谢

**Comment by johnjim0816** [comment]
> > 
> 
> 那请问您方便回答一下我的问题吗？上图中的代码是本书配套的代码。

写的代码形式不一样，数学原理都是一样的
