### ISSUE TITLE
电子版94页和102问题请教

### ISSUE THREAD

**Issue by QUIlToT** [datawhalechina/easy-rl#96]
作者您好，下图画红线的地方应该是Sa，对吧？

<img width="972" alt="微信截图_20220502155618" src="https://user-images.githubusercontent.com/72594017/166202742-a1737ef6-d40f-42d5-92b6-1a5faefe761a.png">

还有另外一个问题，下图红圈标出的at是不是改为at+1更好呢？还是我理解的不对？请您指教哈~

![微信图片编辑_20220502160216](https://user-images.githubusercontent.com/72594017/166203320-fc2a4eae-b7f2-4453-8806-41fa08be78ec.jpg)

**Comment by qiwang067** [comment]
> 作者您好，下图画红线的地方应该是Sa，对吧？
> 
> <img alt="微信截图_20220502155618" width="972" src="https://user-images.githubusercontent.com/72594017/166202742-a1737ef6-d40f-42d5-92b6-1a5faefe761a.png">
> 
> 还有另外一个问题，下图红圈标出的at是不是改为at+1更好呢？还是我理解的不对？请您指教哈~
> 
> ![微信图片编辑_20220502160216](https://user-images.githubusercontent.com/72594017/166203320-fc2a4eae-b7f2-4453-8806-41fa08be78ec.jpg)

@QUIlToT ，感谢您的反馈:+1:，94页中的下图红框的地方应该是  $s_a$。

![image](https://user-images.githubusercontent.com/22296010/166210386-e1c21fd4-f4ef-4a2d-9d21-129945de72b0.png)
关于102页，需要修改的地方如下图所示，这里的 $a$ 没有问题，就是一个能让 Q 值最大的动作的变量。
![image](https://user-images.githubusercontent.com/22296010/166219681-87012798-df7f-492c-be2e-54bbf3c9bdc4.png)

**Comment by QUIlToT** [comment]
> > 作者您好，下图画红线的地方应该是Sa，对吧？
> > <img alt="微信截图_20220502155618" width="972" src="https://user-images.githubusercontent.com/72594017/166202742-a1737ef6-d40f-42d5-92b6-1a5faefe761a.png">
> > 还有另外一个问题，下图红圈标出的at是不是改为at+1更好呢？还是我理解的不对？请您指教哈~
> > ![微信图片编辑_20220502160216](https://user-images.githubusercontent.com/72594017/166203320-fc2a4eae-b7f2-4453-8806-41fa08be78ec.jpg)
> 
> @QUIlToT ，感谢您的反馈👍，94页中的下图红框的地方应该是 $s_a$。
> 
> ![image](https://user-images.githubusercontent.com/22296010/166210386-e1c21fd4-f4ef-4a2d-9d21-129945de72b0.png) 关于102页，需要修改的地方如下图所示，这里的 $a$ 没有问题，就是一个能让 Q 值最大的动作的变量。 ![image](https://user-images.githubusercontent.com/22296010/166219681-87012798-df7f-492c-be2e-54bbf3c9bdc4.png)

谢谢您的回复！

第二个问题确实是我弄错了，可是我觉得您第二张图片的Q_hat 不改成 Q 好一点，因为我理解您说的这个目标值由目标网络Q_hat产生，在不改的前提下可能更容易区分两个网络之间的关系。

如果不改的话，下图的这里修改成Q_hat是否更好的一点呢？

谢谢！

<img width="930" alt="微信截图_20220502195857" src="https://user-images.githubusercontent.com/72594017/166230665-5cdda619-8e15-45c3-a175-7159f071d088.png">

**Comment by qiwang067** [comment]
> > > 作者您好，下图画红线的地方应该是Sa，对吧？
> > > <img alt="微信截图_20220502155618" width="972" src="https://user-images.githubusercontent.com/72594017/166202742-a1737ef6-d40f-42d5-92b6-1a5faefe761a.png">
> > > 还有另外一个问题，下图红圈标出的at是不是改为at+1更好呢？还是我理解的不对？请您指教哈~
> > > ![微信图片编辑_20220502160216](https://user-images.githubusercontent.com/72594017/166203320-fc2a4eae-b7f2-4453-8806-41fa08be78ec.jpg)
> > 
> > 
> > @QUIlToT ，感谢您的反馈👍，94页中的下图红框的地方应该是 $s_a$。
> > ![image](https://user-images.githubusercontent.com/22296010/166210386-e1c21fd4-f4ef-4a2d-9d21-129945de72b0.png) 关于102页，需要修改的地方如下图所示，这里的 $a$ 没有问题，就是一个能让 Q 值最大的动作的变量。 ![image](https://user-images.githubusercontent.com/22296010/166219681-87012798-df7f-492c-be2e-54bbf3c9bdc4.png)
> 
> 谢谢您的回复！
> 
> 第二个问题确实是我弄错了，可是我觉得您第二张图片的Q_hat 不改成 Q 好一点，因为我理解您说的这个目标值由目标网络Q_hat产生，在不改的前提下可能更容易区分两个网络之间的关系。
> 
> 如果不改的话，下图的这里修改成Q_hat是否更好的一点呢？
> 
> 谢谢！
> 
> <img alt="微信截图_20220502195857" width="930" src="https://user-images.githubusercontent.com/72594017/166230665-5cdda619-8e15-45c3-a175-7159f071d088.png">

@QUIlToT  感谢您的反馈:+1:，参考您的建议，修改如下图所示：
![image](https://user-images.githubusercontent.com/22296010/167279540-5b6f44a2-340f-4568-8c29-f11667348895.png)

**Comment by QUIlToT** [comment]
> > > > 作者您好，下图画红线的地方应该是Sa，对吧？
> > > > <img alt="微信截图_20220502155618" width="972" src="https://user-images.githubusercontent.com/72594017/166202742-a1737ef6-d40f-42d5-92b6-1a5faefe761a.png">
> > > > 还有另外一个问题，下图红圈标出的at是不是改为at+1更好呢？还是我理解的不对？请您指教哈~
> > > > ![微信图片编辑_20220502160216](https://user-images.githubusercontent.com/72594017/166203320-fc2a4eae-b7f2-4453-8806-41fa08be78ec.jpg)
> > > 
> > > 
> > > @QUIlToT ，感谢您的反馈👍，94页中的下图红框的地方应该是 $s_a$。
> > > ![image](https://user-images.githubusercontent.com/22296010/166210386-e1c21fd4-f4ef-4a2d-9d21-129945de72b0.png) 关于102页，需要修改的地方如下图所示，这里的 $a$ 没有问题，就是一个能让 Q 值最大的动作的变量。 ![image](https://user-images.githubusercontent.com/22296010/166219681-87012798-df7f-492c-be2e-54bbf3c9bdc4.png)
> > 
> > 
> > 谢谢您的回复！
> > 第二个问题确实是我弄错了，可是我觉得您第二张图片的Q_hat 不改成 Q 好一点，因为我理解您说的这个目标值由目标网络Q_hat产生，在不改的前提下可能更容易区分两个网络之间的关系。
> > 如果不改的话，下图的这里修改成Q_hat是否更好的一点呢？
> > 谢谢！
> > <img alt="微信截图_20220502195857" width="930" src="https://user-images.githubusercontent.com/72594017/166230665-5cdda619-8e15-45c3-a175-7159f071d088.png">
> 
> @QUIlToT 感谢您的反馈👍，参考您的建议，修改如下图所示： ![image](https://user-images.githubusercontent.com/22296010/167279540-5b6f44a2-340f-4568-8c29-f11667348895.png)

谢谢您的耐心回复

**Comment by qiwang067** [comment]
> > > > > 作者您好，下图画红线的地方应该是Sa，对吧？
> > > > > <img alt="微信截图_20220502155618" width="972" src="https://user-images.githubusercontent.com/72594017/166202742-a1737ef6-d40f-42d5-92b6-1a5faefe761a.png">
> > > > > 还有另外一个问题，下图红圈标出的at是不是改为at+1更好呢？还是我理解的不对？请您指教哈~
> > > > > ![微信图片编辑_20220502160216](https://user-images.githubusercontent.com/72594017/166203320-fc2a4eae-b7f2-4453-8806-41fa08be78ec.jpg)
> > > > 
> > > > 
> > > > @QUIlToT ，感谢您的反馈👍，94页中的下图红框的地方应该是 $s_a$。
> > > > ![image](https://user-images.githubusercontent.com/22296010/166210386-e1c21fd4-f4ef-4a2d-9d21-129945de72b0.png) 关于102页，需要修改的地方如下图所示，这里的 $a$ 没有问题，就是一个能让 Q 值最大的动作的变量。 ![image](https://user-images.githubusercontent.com/22296010/166219681-87012798-df7f-492c-be2e-54bbf3c9bdc4.png)
> > > 
> > > 
> > > 谢谢您的回复！
> > > 第二个问题确实是我弄错了，可是我觉得您第二张图片的Q_hat 不改成 Q 好一点，因为我理解您说的这个目标值由目标网络Q_hat产生，在不改的前提下可能更容易区分两个网络之间的关系。
> > > 如果不改的话，下图的这里修改成Q_hat是否更好的一点呢？
> > > 谢谢！
> > > <img alt="微信截图_20220502195857" width="930" src="https://user-images.githubusercontent.com/72594017/166230665-5cdda619-8e15-45c3-a175-7159f071d088.png">
> > 
> > 
> > @QUIlToT 感谢您的反馈👍，参考您的建议，修改如下图所示： ![image](https://user-images.githubusercontent.com/22296010/167279540-5b6f44a2-340f-4568-8c29-f11667348895.png)
> 
> 谢谢您的耐心回复

客气啦:)
