### ISSUE TITLE
DDPG code error

### ISSUE THREAD

**Issue by XianrenYty** [datawhalechina/easy-rl#98]
https://github.com/datawhalechina/easy-rl/blob/29be2ea96670ec13dbdc50700b754cb62dcc94c2/codes/DDPG/task0.py#L78
```bash
AttributeError: 'PlotConfig' object has no attribute 'test_eps'
```

**Solution**
```python
rewards,ma_rewards = test(cfg,env,agent)
```

**Comment by johnjim0816** [comment]
thx for your fix, but now we have migrated our code to joyrl repo and fix this problem, it will be nice of you to star:https://github.com/johnjim0816/rl-tutorials/tree/master/joyrl
