### ISSUE TITLE
在线阅读的地址打不开了

### ISSUE THREAD

**Issue by SoloPro-Git** [datawhalechina/easy-rl#99]
https://datawhalechina.github.io/easy-rl/ 这个打开后没有内容了

**Comment by qiwang067** [comment]
> https://datawhalechina.github.io/easy-rl/ 这个打开后没有内容了

您好，刚刚测试了一下，我这边网址是可以正常打开的。如果您这边打不开的话，您可以试试看“科学上网”。

**Comment by SoloPro-Git** [comment]
切了代理可以了，感谢感谢

**Comment by qiwang067** [comment]
> 切了代理可以了，感谢感谢

客气啦:)
